= Practical Grails 3 - 1.0 Release
Eric Helgeson
2017-12-01
:jbake-type: post
:jbake-status: published
:jbake-tags: blog
:jbake-description: Updates & what's new in the Practical Grails 3 - 1.0!
:idprefix:


Hello, Everyone! I'm excited to announce the `1.0` release of Practical Grails 3!

If you've purchased previously you can https://www.grails3book.com/resend.html[grab an updated copy.]

If you've not purchased yet get https://www.grails3book.com/early-access.html[your copy today!]

A HUGE thank you to the **500+** people who purchased early access!

NOTE: The book will stay Early Access price until 12/7, so grab your copy today!

=== Living Book

The 1.0 release is not the end - it's the beginning! I have been working on the 3.3.x branch updates for a while but there is so much new I wanted the 1.0 to be based off Grails 3.2.
Please note when you purchase Practical Grails 3 you will receive update through the whole life of Grails 3.x.

The book will continue to grow with new features and feedback as Grails grows.

=== Planned for 1.1

* Grails 3.3.x
* Data Services
* GraphQL intro
* More deployment scenarios
* Feedback from you!

=== G3 Summit

I had a great time at the G3 Summit this year - check out my recap blog post!

https://erichelgeson.github.io/blog/2017/12/02/g3summit/
